In [1]:
import numpy as np

In [2]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.full((3,3), fill_value=True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3))>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
x = np.arange(0,10)
print(x, x[x%2==1])

[0 1 2 3 4 5 6 7 8 9] [1 3 5 7 9]


In [7]:
x[x%2==1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
x = np.arange(10)
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
x.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
np.concatenate([np.arange(10).reshape(2, -1), np.repeat(1, 10).reshape(2, -1)], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.arange(10).reshape(2, -1), np.repeat(2, 10).reshape(2, -1)

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]))

In [12]:
np.concatenate([np.arange(10).reshape(2, -1), np.repeat(1, 10).reshape(2, -1)], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [13]:
x = np.array([1,2,3])
print(np.repeat(x, 3))
print(np.tile(x, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [14]:
print(np.repeat(x, 6))

[1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3]


In [15]:
print(np.tile(x, 6))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [16]:
x = np.array([2,6,1,9,10,3,27])
index = np.where((x>=5)&(x<=10))
x[index]

array([ 6,  9, 10])

In [17]:
def maxx(x,y):
    if x >= y :
        return x
    else:
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [18]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
np.where(a<b, b, a)

array([6, 7, 9, 8, 9, 7, 5])

# Exercise 2

In [19]:
import gdown

gdown.download('https://drive.google.com/file/d/1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB/view?usp=sharing', 'dog.jpeg', fuzzy=True)

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: C:\Users\nguye\OneDrive\Learning\AIO\EXERCISE\MODULE 2\M02EX01\dog.jpeg
100%|█████████████████████████████████████████████████████████████████████████████| 33.7k/33.7k [00:00<00:00, 33.4MB/s]


'dog.jpeg'

In [20]:
import matplotlib.image as mpimg
img = mpimg.imread('dog.jpeg')
gray_img_01 = np.max(img, axis=-1, keepdims=1)/2 + np.min(img, axis=-1, keepdims=1)/2
gray_img_01[0, 0]

array([102.5])

In [21]:
gray_img_02 = np.sum(img, axis=-1, keepdims=1)/3
gray_img_02[0, 0]

array([107.66666667])

In [22]:
x = [0.21,0.72,0.07]
gray_img_03 = np.dot(img[...,:3], x)
gray_img_03[0, 0]

126.22999999999999

In [23]:
gdown.download('https://drive.google.com/file/d/1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq/view?usp=sharing', 'advertising.csv', fuzzy=True)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: C:\Users\nguye\OneDrive\Learning\AIO\EXERCISE\MODULE 2\M02EX01\advertising.csv
100%|█████████████████████████████████████████████████████████████████████████████████████| 4.06k/4.06k [00:00<?, ?B/s]


'advertising.csv'

In [24]:
import pandas as pd
df = pd.read_csv('advertising.csv')
data = df.to_numpy()
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [25]:
df['Sales'].idxmax(), df['Sales'].max()

(175, 27.0)

In [26]:
df['TV'].mean()

147.0425

In [27]:
df[df['Sales']>=20].count()

TV           40
Radio        40
Newspaper    40
Sales        40
dtype: int64

In [28]:
df[df['Sales']>=15].mean()

TV           213.635780
Radio         26.222936
Newspaper     33.090826
Sales         19.193578
dtype: float64

In [29]:
#19?? 20?? 21??

In [53]:
mean_newspaper = df['Newspaper'].mean()
print(mean_newspaper)
filtered = df['Newspaper']
result = (filtered > mean_newspaper)
print(df['Sales'][result].sum())

30.553999999999995
1405.1


In [43]:
mean_sales = df['Sales'].mean()
scores = df['Sales'].apply(lambda x: 'Good' if x > mean_sales else ('Bad' if x < mean_sales else 'Average'))
print(scores[7:10].tolist())

['Bad', 'Bad', 'Good']


In [45]:
closest_value = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argsort()[:1]].values[0]
scores = df['Sales'].apply(lambda x: 'Good' if x > closest_value else ('Bad' if x < closest_value else 'Average'))
print(scores[7:10].tolist())

['Bad', 'Bad', 'Good']


In [47]:
mean_sales = df['Sales'].mean()
scores = df['Sales'].apply(lambda x: 'Good' if x > mean_sales else ('Bad' if x < mean_sales else 'Average'))
print(scores)

0      Good
1       Bad
2       Bad
3      Good
4      Good
       ... 
195     Bad
196     Bad
197     Bad
198    Good
199    Good
Name: Sales, Length: 200, dtype: object


In [48]:
closest_value = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argsort()[:1]].values[0]
scores = df['Sales'].apply(lambda x: 'Good' if x > closest_value else ('Bad' if x < closest_value else 'Average'))
print(scores)

0      Good
1       Bad
2       Bad
3      Good
4      Good
       ... 
195     Bad
196     Bad
197     Bad
198    Good
199    Good
Name: Sales, Length: 200, dtype: object
